config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#index"
  resources :prayers, only: [:create, :index, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prayer.rb
class Prayer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        
    end
end

app/controllers/prayers_controller.rb
class PrayersController < ApplicationController
    def index
        @prayers = Prayer.all
        #@prayers_by_date = @prayers.group(&:created_at.strftime('%Y-%m-%d'))
      
        
        @day = Date.today.strftime("%Y-%m-%d")
        
        # FOR INDEX PAGE
        # <%= calendar do |date| %>
        #     <%= date.day %>
        #     <% if @prayers_by_date[date] %>
        #         <ul>
        #             <% @prayers_by_date[date].each do |prayer| %>
        #                 <li><%= link_to prayer.name, "#" %></li>
        #             <% end %>
        #         </ul>
        #     <% end %>
        # <% end %>
            

        
    end
    
    def new
        @prayer = Prayer.new 
    end
    
    def create
        Prayer.create(prayer_params)
        redirect_to prayers_path
    end
    
    private
    
    def prayer_params
        params.require(:prayer).permit(:name, :email, :request_type, :title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
   def calendar(date = Date.today, &block)
      Calendar.new(self, date, block).table 
   end
   
   class Calendar < Struct.new(:view, :date, :callback)
      HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
      START_DAY = :sunday
      
      delegate :content_tag, to: :view
      
      def table
         content_tag :table, class: "calendar" do 
            header + week_rows 
         end
      end
      
      def header
         content_tag :tr do
             HEADER.map { |day| content_tag :th, day }.join.html_safe
         end
      end
      
      def week_rows
         weeks.map do |week|
             content_tag :tr do
                 week.map { |day| day_cell(day) }.join.html_safe
             end
        end.join.html_safe 
      end
      
      def day_cell(day)
         content_tag :td, view.capture(day, &callback), class: day_classes(day)
      end
      
      def day_classes(day)
         classes = []
         classes << "today" if day == Date.today
         classes << "notmonth" if day.month != date.month
         classes.empty? ? nil : classes.join(" ")
      end
      
      def weeks
         first = date.beginning_of_month.beginning_of_week(START_DAY)
         last = date.end_of_month.end_of_week(START_DAY)
         (first..last).to_a.in_groups_of(7)
      end
   end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prayers_helper.rb
module PrayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Church</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="mySidenav" class="sidenav">
      <a href="javascript: void(0)" class="closebtn" onclick = "closeNav()">&times;</a> 
      <a href="#">About</a>
      <a href="#">Services</a>
      <a href="#">Clients</a>
      <a href="#">Contact</a>
    </div>
    
    <!-- User any element to open the sidenav-->
      
      <div class="row navigation">
          <p class="col-12">Menu</p>
          <span class="col-12" onclick="openNav()"><%= image_tag "cross.png", class: "hamburger" %></span>
          
      </div>
     
    

    
    <%= yield %>
    

    <script>
      /* set the width of the navigation to 250px */
      function openNav(){
        document.getElementById("mySidenav").style.width = "250px";
      }
      
      /* Set the width of the side navigation to 0 */
      function closeNav(){
        document.getElementById("mySidenav").style.width = "0"
      }
    </script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="hero">
    <div class="hero-frosty col-8 offset-2 text-center">
        <h1>Hafa Adai</h1>
        <p>Jesus never promised us a rose garden but will go through the thorns with us.</p>
    </div>
        
</div>

<div class="center-section">
    <div class="overlay">
        <div class="row">
            <div class="col-sm">
                <img src="https://images.unsplash.com/photo-1469467188629-fcc2fdaefa30?dpr=2&auto=format&fit=crop&w=1500&h=1001&q=80&cs=tinysrgb&crop=">
                <div class="box">
                    
                    <h2>I'm New</h2>
                    <p>Find Out What to Expect</p>
                </div>
                
            </div>
            
        
             <div class="col-sm">
                 <%= link_to new_prayer_path do %>
                 <img src="https://images.unsplash.com/photo-1470686164816-830d3688f62c">
                 <div class="box">
                    <h2>Prayer</h2>
                    <p>Submit Your Request</p>
                 </div>
                 <% end %>
            </div>
            
             <div class="col-sm">
                 <img src="https://images.unsplash.com/photo-1473122430480-d00e6dd25ba8">
                 <div class="box">
                     
                    <h2>Calendar</h2>
                    <p>View Our Montly Schedule</p>
                 </div>
             </div>
        </div>
        
        <br class="clear"></br>
        
        <div class="row">
            <div class="col-12">
                <img src="https://images.unsplash.com/photo-1473508476344-269a87b502ee">
                <div class="pink-frosty text-center">
                    <br><br>
                    <h2>Times And Directions</h2>
                    <p>Sunday Mornings @ 1030-service</p>
                    <p>Friday Night @8pm Fire and deliverance</p>
                    <p>122 Tun Jose Toves Way</p>
                </div>
                
            </div>
        </div>
    </div>

</div>

app/views/prayers/index.html.erb
<% @prayers.each do |prayer|%>
    <div>
        <h1><%= prayer.title %></h1>
        <p>From: <%= prayer.name %></p>
        <p>Email: <%= prayer.email %></p>
        <p>Request-type: <%= prayer.request_type %></p>
        <p>Prayer Description: <%= prayer.description %></p>
        <h1>Prayer Created at: <%= prayer.created_at.strftime("%Y-%m-%d") %></h1>
        
    </div>
<% end %>


<hr><hr>


<hr><hr>


<%= calendar do |date| %>
    <%= date.day %>
    <% @prayers.each do |prayer| %>
        <% if prayer.created_at.strftime("%Y-%m-%d") == date.to_s %>
            <ul
                <li>
                    <%= prayer.name %>
                    <ul><%= prayer.title %></ul>
                </li>
            </ul>
        <% else %>
            <p>Not here <%=date %></p>
        <% end %>
    <% end %>
<% end %>
    

app/views/prayers/new.html.erb
<div class="col-12 new-prayer">
    
</div>
<div class="col-12 col-sm-10 offset-sm-1">
    <ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="btn btn-info" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Submit Prayer Online</a>
  </li>

</ul>

<br>
<div class="col-12 col-sm-10 offset-sm-1">
  
    
<div class="collapse" id="collapseExample">
  <div class="card card-block">
    <h1>New Prayer</h1>
    <%= simple_form_for @prayer do |f| %>
        <%= f.input :name, placeholder: "Your Name" %>
        <%= f.input :email, label: false, placeholder:"Email" %>
        <%= f.input :request_type, label: "Type Of Request", :collection => %w[Financial Sickness Marriage Death] %>
        <%= f.input :title, label: "Short Summary Title Of Request" %>
        <%= f.input :description, label: false, :as => :text, :input_html => { :rows => 7 , :style => 'width: 100%'}%>
        <%= f.submit "Send Prayer", class: "btn btn-success" %>
    <% end %>
  </div>
</div>
</div>
<p>Prayer is the practice of the presence of God. It is the place where pride is abandoned, hope is lifted, and supplication is made. Prayer is the place for admitting our need, for adopting humility, and claiming dependence upon God. Prayer is the needful practice of the Christian. Prayer is the exercise of faith and hope. Prayer is the privilege of touching the heart of the Father through His Son, Jesus Christ our Lord.</p>

<p><i>Draw near to God and He will draw near to you. James: 4:8</i></p>

<p>Be anxious for nothing, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all comprehension, shall guard your hearts and your minds in Christ Jesus. Phil. 4:6-7</p>
</div>